language: python
sudo: required
python: 2.7
env:
  - TOX_ENV=py27-lint
  - TOX_ENV=py34-lint
  - TOX_ENV=py27-lint-readme
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py27-lint-docstring-include-list

before_install:
  # Install Singularity
  - sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev squashfs-tools wget git
  - wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
  - echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
  - echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
  - source ~/.bashrc
  - mkdir -p $GOPATH/src/github.com/sylabs
  - cd $GOPATH/src/github.com/sylabs
  - git clone https://github.com/sylabs/singularity.git
  - cd singularity
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - cd $GOPATH/src/github.com/sylabs/singularity
  - ./mconfig
  - make -C builddir
  - sudo make -C builddir install


install:
  # Setup git to allow git operations.
  - git config --global user.name "Travis Test User"
  - git config --global user.email "galaxy_test@galaxyproject.org"
  - pip install tox coveralls

script: tox -e $TOX_ENV

after_success:
  - coveralls
